[template]
src   = "runit-sv-restart-run.tmpl"
dest  = "/etc/service/runit-sv-restart/runit"
#owner = "app"
#group = "app"
mode  = "0644"
keys = [
"/runit",
]
#check_cmd = "/app/bin/check {{ .src }}"
#reload_cmd = "service restart example"
reload_cmd = "sv restart runit-sv-restart"
