[template]
src   = "privoxy-config.tmpl"
dest  = "/etc/service/privoxy/config"
#owner = "app"
#group = "app"
mode  = "0644"
keys = [
"/port",
]
check_cmd = "privoxy --no-daemon --config-test {{ .src }}"
reload_cmd = "sv reload privoxy"
