[template]
src   = "privoxy-check.tmpl"
dest  = "/etc/service/privoxy/check"
#owner = "app"
#group = "app"
mode  = "0755"
keys = [
"/port",
]
#check_cmd = "/app/bin/check {{ .src }}"
#reload_cmd = "service restart example"
#reload_cmd = "sv restart privoxy"
