[template]
src   = "confd.vars.tmpl"
dest  = "/etc/service/confd/confd.vars"
#owner = "app"
#group = "app"
mode  = "0644"
keys = [
"/runit",
]
#check_cmd = "/app/bin/check {{ .src }}"
#reload_cmd = "service restart example"
#reload_cmd = "sv restart confd"
