[template]
src   = "torrc.tmpl"
dest  = "/etc/tor/torrc"
#dest  = "/etc/service/tor/torrc"
#owner = "app"
#group = "app"
mode  = "0644"
keys = [
"/port",
"/tor",
]
#check_cmd = "/usr/bin/tor --defaults-torrc /usr/share/tor/tor-service-defaults-torrc --verify-config -f {{ .src }}"
#reload_cmd = "service restart example"
check_cmd = "tor --verify-config -f {{ .src }}"
reload_cmd = "sv reload tor"
