[template]
src   = "torrc.9060.tmpl"
dest  = "/etc/tor/torrc.9060"
#dest  = "/etc/service/tor/torrc.9060"
#owner = "app"
#group = "app"
mode  = "0644"
keys = [
"/port",
"/tor",
]
#check_cmd = "/app/bin/check {{ .src }}"
#reload_cmd = "service restart example"
reload_cmd = "sv reload tor"
